spring.application.name=segurplan
# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/SegurPlan
spring.datasource.username=postgres
spring.datasource.password=emer
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# No modificar las tablas existentes
spring.jpa.hibernate.ddl-auto=none
# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SERVIDOR
server.port=8080